Week_01/G20200343040215/LeetCode_189_0215.java, Week_01/G20200343040215/LeetCode_1_0215.java, Week_01/G20200343040215/LeetCode_21_0215.java, Week_01/G20200343040215/LeetCode_26_0215.java, Week_01/G20200343040215/LeetCode_283_0215.java, Week_01/G20200343040215/LeetCode_66_0215.java
=> 0215_Week01 (java)

Week_01/G20200343040283/LeetCode_189_0283.php, Week_01/G20200343040283/LeetCode_1_0283.php, Week_01/G20200343040283/LeetCode_26_0283.php, Week_01/G20200343040283/LeetCode_283_0283.php, Week_01/G20200343040283/LeetCode_66_0283.php, Week_01/G20200343040283/LeetCode_88_0283.php
=> 0283_Week01（php）

Week_01/G20200447010287/LeetCode_189_1287.js, Week_01/G20200447010287/LeetCode_1_1287.js, Week_01/G20200447010287/LeetCode_21_1287.js, Week_01/G20200447010287/LeetCode_26_1287.js, Week_01/G20200447010287/LeetCode_283_1287.js, Week_01/G20200447010287/LeetCode_66_1287.js, Week_01/G20200447010287/LeetCode_88_1287.js
=> 1287_Week01(js)

Week_01/G20200343040215/LeetCode_189_0215.js, Week_01/G20200343040215/LeetCode_1_0215.js, Week_01/G20200343040215/LeetCode_21_0215.js, Week_01/G20200343040215/LeetCode_26_0215.js, Week_01/G20200343040215/LeetCode_283_0215.js, Week_01/G20200343040215/LeetCode_66_0215.js, Week_01/G20200343040215/LeetCode_88_0215.js
=> 0215_Week01(js)

Week_01/G20200343040093/LeetCode_1_0093.java, Week_01/G20200343040093/LeetCode_283_0093.java, Week_01/G20200343040093/NOTE.md
=> 0093_Week01（Java）

Week_01/G20200343040089/LeetCode_21_0089.cpp, Week_01/G20200343040089/LeetCode_26_0089.cpp
=> 0089_Week01(C++)

Week_01/G20200343040319/LeetCode_1_0319.java, Week_01/G20200343040319/LeetCode_21_0319.java, Week_01/G20200343040319/LeetCode_26_0319.java, Week_01/G20200343040319/LeetCode_88_0319.java
=> 0319_Week01（Java）

Week_01/G20200343040033/LeetCode_1_0033.py, Week_01/G20200343040033/LeetCode_2_0033.py, Week_01/G20200343040033/LeetCode_4_0033.py
=> 0033_Week01（py）

Week_01/G20200343040211/LeetCode_189_0211.java, Week_01/G20200343040211/LeetCode_26_0211.java
=> 0211_Week01

Week_01/G20200343040227/LeetCode_01_0227.java, Week_01/G20200343040227/LeetCode_189_0227.java, Week_01/G20200343040227/LeetCode_21_0227.java, Week_01/G20200343040227/LeetCode_26_0227.java, Week_01/G20200343040227/LeetCode_283_0227.java, Week_01/G20200343040227/LeetCode_66_0227.java, Week_01/G20200343040227/LeetCode_88_0227.java
=> 0227_Week01（java）

Week_01/G20200343040279/LeetCode_189_0279.java, Week_01/G20200343040279/LeetCode_1_0279.java, Week_01/G20200343040279/LeetCode_21_0279.java, Week_01/G20200343040279/LeetCode_26_0279.java, Week_01/G20200343040279/LeetCode_283_0279.java, Week_01/G20200343040279/LeetCode_66_0279.java, Week_01/G20200343040279/LeetCode_88_0279.java
=> 0279_Week01(java)

Week_01/G20200343040337/LeetCode_189_0337.js, Week_01/G20200343040337/LeetCode_1_0337.js, Week_01/G20200343040337/LeetCode_21_0337.js, Week_01/G20200343040337/LeetCode_26_0337.js, Week_01/G20200343040337/LeetCode_283_0337.js, Week_01/G20200343040337/LeetCode_66_0337.js, Week_01/G20200343040337/LeetCode_88_0337.js, Week_01/G20200343040337/NOTE.md
=> 0337_Week01（js）

Week_01/G20200343040063/LeetCode_189_0063.java, Week_01/G20200343040063/LeetCode_1_0063.java, Week_01/G20200343040063/LeetCode_21_0063.java, Week_01/G20200343040063/LeetCode_26_0063.java, Week_01/G20200343040063/LeetCode_283_0063.java, Week_01/G20200343040063/LeetCode_66_0063.java, Week_01/G20200343040063/LeetCode_88_0063.java
=> 0063_Week01(Java)

Week_01/G20200343040145/LeetCode_1_0145.java, Week_01/G20200343040145/LeetCode_26_0145.java, Week_01/G20200343040145/LeetCode_283_0145.java, Week_01/G20200343040145/LeetCode_66_0145.java
=> 0145_Week01(java)

Week_01/G20200343040323/LeetCode_26_0323.c, Week_01/G20200343040323/LeetCode_283_0323.c
=> 0323_Week01(C)

Week_01/G20200343040317/LeetCode_141_0317.java, Week_01/G20200343040317/LeetCode_189_0317.java, Week_01/G20200343040317/LeetCode_1_0317.java, Week_01/G20200343040317/LeetCode_206_0317.java, Week_01/G20200343040317/LeetCode_21_0317.java, Week_01/G20200343040317/LeetCode_26_0317.java, Week_01/G20200343040317/LeetCode_283_0317.java, Week_01/G20200343040317/LeetCode_66_0317.java, Week_01/G20200343040317/LeetCode_88_0317.java
=> 0317_Week01(java)

Week_01/G20200343040213/LeetCode_189_0213.java, Week_01/G20200343040213/LeetCode_1_0213.java, Week_01/G20200343040213/LeetCode_21_0213.java, Week_01/G20200343040213/LeetCode_26_0213.java, Week_01/G20200343040213/LeetCode_283_0213.java, Week_01/G20200343040213/LeetCode_66_0213.java, Week_01/G20200343040213/LeetCode_88_0213.java
=> 0213_Week01(java)

Week_01/G20200343040289/1.two-sum.js, Week_01/G20200343040289/189.rotate-array.js, Week_01/G20200343040289/21.merge-two-sorted-lists.js, Week_01/G20200343040289/26.remove-duplicates-from-sorted-array.js, Week_01/G20200343040289/283.move-zeroes.js, Week_01/G20200343040289/66.plus-one.js, Week_01/G20200343040289/88.merge-sorted-array.js
leetcode-cn.com/problems/remove-duplicates-from-sorted-array
leetcode-cn.com/problems/rotate-array
leetcode-cn.com/problems/merge-two-sorted-lists
leetcode-cn.com/problems/merge-sorted-array
leetcode-cn.com/problems/two-sum
leetcode-cn.com/problems/move-zeroes
leetcode-cn.com/problems/plus-one
=> 0289_Week01(JS)

Week_01/G20200343040105/MergeSortedArray.cpp, Week_01/G20200343040105/MoveZeroes.cpp, Week_01/G20200343040105/RotateArray.cpp, Week_01/G20200343040105/TowSum.cpp
=> 0105_Week01(c++)

Week_01/G20200343040001/LeetCode_189_0001.js, Week_01/G20200343040001/LeetCode_1_0001.js, Week_01/G20200343040001/LeetCode_283_0001.js
=> 0001_week01(js)

Week_01/G20200343040297/1_two_sum.py, Week_01/G20200343040297/283_move_zero.py, Week_01/G20200343040297/66_plus_one.py, Week_01/G20200343040297/88_merge_sorted_array.py
=> 0297_Week01(py)

Week_01/G20200343040027/LeetCode_189_0027.py.java, Week_01/G20200343040027/LeetCode_26_0027.java
=> 0027_Week01（java）

Week_01/G20200343040185/LeetCode_189_0185.js, Week_01/G20200343040185/LeetCode_21_0185.js, Week_01/G20200343040185/LeetCode_26_0185.js, Week_01/G20200343040185/LeetCode_88_0185.js
=> 0185_Week01(js)

Week_01/G20200343040069/LeetCode_1_0069.java, Week_01/G20200343040069/LeetCode_283_0069.java
=> 0069_week01(java)

Week_01/G20200343040291/LeetCode_189_0291.c, Week_01/G20200343040291/LeetCode_26_0291.c, Week_01/G20200343040291/LeetCode_283_0291.c
=> 0291_Week01(C)

Week_02/G20200343040001/LeetCode_1_0001.js, Week_02/G20200343040001/LeetCode_49_0001.js, Week_02/G20200343040001/LeetCode_641_0001.js
=> 0001_week02(js)

Week_02/G20200343040147/DequeCase.java, Week_02/G20200343040147/LeetCode_1_0147.java, Week_02/G20200343040147/LeetCode_42_0147.java, Week_02/G20200343040147/LeetCode_49_0147.java, Week_02/G20200343040147/LeetCode_641_0147.java, Week_02/G20200343040147/NOTE.md
=> 0147_Week02（java）

Week_02/G20200343040289/1.two-sum.js, Week_02/G20200343040289/42.trapping-rain-water.js, Week_02/G20200343040289/49.group-anagrams.js, Week_02/G20200343040289/641.design-circular-deque.js
https://leetcode-cn.com/problems/two-sum/description/
https://leetcode-cn.com/problems/group-anagrams/
https://leetcode.com/problems/design-circular-deque
https://leetcode.com/problems/trapping-rain-water/
=> 0289_Week02（js）

Week_02/G20200343040241/LeetCode_42_0241.java, Week_02/G20200343040241/LeetCode_49_0241.java, Week_02/G20200343040241/LeetCode_641_0241.java, Week_02/G20200343040241/NOTE.md
=> 0241_Week02（java）

Week_02/G20200343040095/Solution-1.java, Week_02/G20200343040095/Solution-42.java, Week_02/G20200343040095/Solution-49.java
=> 0095_Week02

Week_01/G20200343040009/homework/src/com/studyWeek1/ListNode.java, Week_01/G20200343040009/homework/src/com/studyWeek1/MaxArea.java, Week_01/G20200343040009/homework/src/com/studyWeek1/Merge.java, Week_01/G20200343040009/homework/src/com/studyWeek1/MergeTwoLists.java, Week_01/G20200343040009/homework/src/com/studyWeek1/MoveZeroes.java, Week_01/G20200343040009/homework/src/com/studyWeek1/PlusOne.java, Week_01/G20200343040009/homework/src/com/studyWeek1/RemoveDuplicates.java, Week_01/G20200343040009/homework/src/com/studyWeek1/Rotate.java, Week_01/G20200343040009/homework/src/com/studyWeek1/TwoSum.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode1.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode15.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode20.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode242.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode49.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode641.java, Week_01/G20200343040009/homework/src/com/studyWeek2/LeetCode84.java
=> 0009_Week02(Java)

Week_02/G20200343040307/LeetCode_42_0307.swift, Week_02/G20200343040307/LeetCode_49_0307.swift, Week_02/G20200343040307/LeetCode_641_0307.swift, Week_02/G20200343040307/NOTE.md
=> 0307_Week02（Swift）

Week_02/G20200343040229/LeetCode_49_0229.go, Week_02/G20200343040229/LeetCode_641_0229.go
=> 0229_Week02(Go)

Week_02/G20200343040159/LeetCode_1_0159.java, Week_02/G20200343040159/LeetCode_49_0159.java, Week_02/G20200343040159/LeetCode_641_0159.java
=> 0159_Week02(Java)

Week_02/G20200343040069/LeetCode_1_0069.java, Week_02/G20200343040069/LeetCode_42_0069.java, Week_02/G20200343040069/LeetCode_49_0069.java, Week_02/G20200343040069/LeetCode_641_0069.java
=> 0069_week2(java)

Week_02/G20200343040063/LeetCode_1_0063.java, Week_02/G20200343040063/LeetCode_42_0063.java, Week_02/G20200343040063/LeetCode_49_0063.java, Week_02/G20200343040063/LeetCode_641_0063.java
=> 0063_Week02(Java)

Week_02/G20200343040317/LeetCode_1_0317.java, Week_02/G20200343040317/LeetCode_239_0317.java, Week_02/G20200343040317/LeetCode_42_0317.java, Week_02/G20200343040317/LeetCode_49_0317.java, Week_02/G20200343040317/LeetCode_641_0317.java, Week_02/G20200343040317/LeetCode_641_0317_第二遍.java, Week_02/G20200343040317/LeetCode_84_0317.java
=> 0317_Week02(java)

Week_02/G20200343040173/LeetCode_49_0173_1.java, Week_02/G20200343040173/LeetCode_49_0173_2.java, Week_02/G20200343040173/LeetCode_641_0173_1.java, Week_02/G20200343040173/LeetCode_641_0173_2.java, Week_02/G20200343040173/LeetCode_641_0173_3.java, Week_02/G20200343040173/NOTE.md
=> 0173_Week02(Java)

Week_02/G20200343040227/LeetCode_01_0227.java, Week_02/G20200343040227/LeetCode_42_0227.java, Week_02/G20200343040227/LeetCode_49_0227.java, Week_02/G20200343040227/LeetCode_641_0227.java, Week_02/G20200343040227/NOTE.md
=> 0227_Week02（Java）

Week_02/G20200343040079/LeetCode_155_0079.py, Week_02/G20200343040079/LeetCode_20_0079.py, Week_02/G20200343040079/LeetCode_239_0079.py, Week_02/G20200343040079/LeetCode_42_0079.py, Week_02/G20200343040079/LeetCode_49_0079.py, Week_02/G20200343040079/LeetCode_641_0079.py, Week_02/G20200343040079/LeetCode_84_0079.py, Week_02/G20200343040079/NOTE.md
=> 0079_Week02（py）

Week_02/G20200343040247/LeedCode_1_0247.js, Week_02/G20200343040247/LeedCode_41_0247.js, Week_02/G20200343040247/LeedCode_49_0247.js, Week_02/G20200343040247/LeedCode_641_0247.js, Week_02/G20200343040247/NOTE.md
=> 0247_Week02(js)

Week_02/G20200343040105/Tow-sum.cpp, Week_02/G20200343040105/Trapping-rain-water.cpp, Week_02/G20200343040105/groupAnagrams.cpp
=> 0105-Week_02(cpp)

Week_01/G20200343040271/LeetCode_189_0271.java, Week_01/G20200343040271/LeetCode_21_0271.java, Week_02/G20200343040271/LeetCode_1_0271.java, Week_02/G20200343040271/LeetCode_42_0271.java, Week_02/G20200343040271/LeetCode_49_0271.java, Week_02/G20200343040271/LeetCode_641_0271.java, Week_02/G20200343040271/LeetCode_641_0271_ArrayDeque.java, Week_02/G20200343040271/LeetCode_641_0271_LinkedDeque.java, Week_02/G20200343040271/LeetCode_641_0271_MyArrayCircularDeque.java
=> 0271_Week02（java）

Week_02/G20200343040045/LeetCode_42_0045.cpp, Week_02/G20200343040045/LeetCode_49_0045.cpp, Week_02/G20200343040045/LeetCode_641_0045.cpp
=> 0045_Week02（C++）

Week_02/G20200343040297/155_min_stack.py, Week_02/G20200343040297/1_two_sum.py, Week_02/G20200343040297/20_valid-parentheses.py, Week_02/G20200343040297/239_sliding_window_maximum.py, Week_02/G20200343040297/242_valid_anagram.py, Week_02/G20200343040297/42_trapping_rain_water.py, Week_02/G20200343040297/49_group_anagrams.py, Week_02/G20200343040297/641_design_circular_deque.py, Week_02/G20200343040297/84_largest_rectangle_in_histogram.py
=> 0297_Week02(py)

Week_02/G20200343040033/LeetCode_1_0033.py, Week_02/G20200343040033/LeetCode_3_0033.py, Week_02/G20200343040033/LeetCode_4_0033.py, Week_02/G20200343040033/LeetCode_5_0033.py, Week_03/G20200343040033/week3-01.py, Week_03/G20200343040033/week3-02.py, Week_03/G20200343040033/week3-03.py, Week_03/G20200343040033/week3-04.py
=> 0033_Week02（py）

Week_02/G20200343040163/LeetCode_1_0163.cpp, Week_02/G20200343040163/LeetCode_20_0163.cpp, Week_02/G20200343040163/LeetCode_84_0163.cpp
=> 0163_Week02（cpp）

Week_02/G20200343040227/LeetCode_242_0027.py.java, Week_02/G20200343040227/LeetCode_42_0027.java
=> 0277_Week02（java）

Week_03/G20200343040175/LeetCode_589_0175.py, Week_03/G20200343040175/LeetCode_590_0175.py
=> 0175_Week03(py)

Week_01/G20200343040307/LeetCode_88_0307.swift, Week_03/G20200343040307/LeetCode_144_0307.swift, Week_03/G20200343040307/LeetCode_429_0307.swift, Week_03/G20200343040307/LeetCode_590_0307.swift, Week_03/G20200343040307/LeetCode_598_0307.swift
只来得及做树的这四道算法题。有一整天用在了练习实战题目了，周末两天太忙没时间做剩下的四道题目。下周好像量比较少，把这周的补上。
=> 0307_Week03( Swift )

Week_03/G20200343040043/LeetCode_144_0043.go, Week_03/G20200343040043/LeetCode_236_0043.go, Week_03/G20200343040043/LeetCode_429_0043.go, Week_03/G20200343040043/LeetCode_589_0043.go, Week_03/G20200343040043/LeetCode_590_0043.go
=> 0043_Week03（golang）

Week_03/G20200343040289/105.construct-binary-tree-from-preorder-and-inorder-traversal.js, Week_03/G20200343040289/144.binary-tree-preorder-traversal.js, Week_03/G20200343040289/236.lowest-common-ancestor-of-a-binary-tree.js, Week_03/G20200343040289/429.n-ary-tree-level-order-traversal.js, Week_03/G20200343040289/46.permutations.js, Week_03/G20200343040289/47.permutations-ii.js, Week_03/G20200343040289/589.n-ary-tree-preorder-traversal.js, Week_03/G20200343040289/590.n-ary-tree-postorder-traversal.js, Week_03/G20200343040289/77.combinations.js
简单：
https://leetcode-cn.com/problems/n-ary-tree-postorder-traversal/
https://leetcode-cn.com/problems/n-ary-tree-preorder-traversal/description/
中等：
https://leetcode-cn.com/problems/binary-tree-preorder-traversal/
https://leetcode-cn.com/problems/n-ary-tree-level-order-traversal/
https://leetcode-cn.com/problems/lowest-common-ancestor-of-a-binary-tree/
https://leetcode-cn.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
https://leetcode-cn.com/problems/combinations/
https://leetcode-cn.com/problems/permutations/
https://leetcode-cn.com/problems/permutations-ii/
=> 0289_Week03 (js)

Week_03/G20200343040091/LeetCode_144_0091.java, Week_03/G20200343040091/LeetCode_589_0091.java, Week_03/G20200343040091/LeetCode_590_0091.java
=> 0091_Week03（java）

Week_03/G20200343040093/LeetCode_589_0093.java, Week_03/G20200343040093/LeetCode_590_0093.java, Week_03/G20200343040093/NOTE.md
=> 0093_Week03(Java)

Week_03/G20200343040063/LeetCode_144_0063.java, Week_03/G20200343040063/LeetCode_589_0063.java, Week_03/G20200343040063/LeetCode_590_0063.java, Week_03/G20200343040063/LeetCode_70_0063.java
=> 0063_Week03(Java)

Week_03/G20200343040273/LeetCode_144_0273.php, Week_03/G20200343040273/LeetCode_347_0273.php, Week_03/G20200343040273/LeetCode_94_0273.php, Week_03/G20200343040273/LeetCode_面试49_0273.php
=> 0273_Week03（php）

Week_03/G20200343040001/LeetCode_144_0001.js, Week_03/G20200343040001/LeetCode_236_0001.js, Week_03/G20200343040001/LeetCode_429_0001.js, Week_03/G20200343040001/LeetCode_589_0001.js, Week_03/G20200343040001/LeetCode_590_0001.js
=> 0001_Week03（js）

Week_03/G20200343040291/LeetCode_144_0291.c, Week_03/G20200343040291/LeetCode_429_0291.c, Week_03/G20200343040291/LeetCode_589_0291.c, Week_03/G20200343040291/LeetCode_590_0291.c
=> 0291_Week03(C)

Week_03/G20200343040229/LeetCode_105_0229.go, Week_03/G20200343040229/LeetCode_114_0229.go, Week_03/G20200343040229/LeetCode_1162_0229.go, Week_03/G20200343040229/LeetCode_151_0229.go, Week_03/G20200343040229/LeetCode_198_0229.go, Week_03/G20200343040229/LeetCode_46_0229.go, Week_03/G20200343040229/LeetCode_589_0229.go, Week_03/G20200343040229/LeetCode_77_0229.go, Week_03/G20200343040229/LeetCode_820_0229.go, Week_03/G20200343040229/LeetCode_892_0229.go, Week_03/G20200343040229/LeetCode_914_0229.go, Week_03/G20200343040229/LeetCode_999_0229.go
=> 0229_Week03(Go)

Week_03/G20200343040251/LeetCode_105_0251.js, Week_03/G20200343040251/LeetCode_144_0251.js, Week_03/G20200343040251/LeetCode_236_0251.js, Week_03/G20200343040251/LeetCode_429_0251.js, Week_03/G20200343040251/LeetCode_46_0251.js, Week_03/G20200343040251/LeetCode_47_0251.js, Week_03/G20200343040251/LeetCode_589_0251.js, Week_03/G20200343040251/LeetCode_590_0251.js, Week_03/G20200343040251/LeetCode_77_0251.js
=> 0251_Week03(js)

Week_03/G20200343040327/LeetCode_105_0327.py, Week_03/G20200343040327/LeetCode_144_0327.py, Week_03/G20200343040327/LeetCode_236_0327.py, Week_03/G20200343040327/LeetCode_429_0327.py, Week_03/G20200343040327/LeetCode_46_0327.py, Week_03/G20200343040327/LeetCode_47_0327.py, Week_03/G20200343040327/LeetCode_589_0327.py, Week_03/G20200343040327/LeetCode_590_0327.py, Week_03/G20200343040327/LeetCode_77_0327.py
=> 0327_Week03(py)

Week_03/G20200343040277/LeetCode_105_0277.py, Week_03/G20200343040277/LeetCode_144_0277.py, Week_03/G20200343040277/LeetCode_589_0277.py, Week_03/G20200343040277/LeetCode_590_0277.py, Week_03/G20200343040277/LeetCode_94_0277.py
=> 0277_Week03（py）

Week_03/G20200343040227/LeetCode_105_0227.java, Week_03/G20200343040227/LeetCode_144_0227.java, Week_03/G20200343040227/LeetCode_236_0227.java, Week_03/G20200343040227/LeetCode_429_0227.java, Week_03/G20200343040227/LeetCode_46_0227.java, Week_03/G20200343040227/LeetCode_47_0227.java, Week_03/G20200343040227/LeetCode_589_0227.java, Week_03/G20200343040227/LeetCode_590_0227.java, Week_03/G20200343040227/LeetCode_77_0227.java
=> 0227_Week03（java）

Week_03/G20200343040271/LeetCode_144_0271.java, Week_03/G20200343040271/LeetCode_236_0271.java, Week_03/G20200343040271/LeetCode_429_0271.java, Week_03/G20200343040271/LeetCode_590_0271.java
=> 0271_Week03(java)

Week_03/G20200343040079/LeetCode_104_0079.py, Week_03/G20200343040079/LeetCode_105_0079.py, Week_03/G20200343040079/LeetCode_111_0079.py, Week_03/G20200343040079/LeetCode_144_0079.py, Week_03/G20200343040079/LeetCode_169_0079.py, Week_03/G20200343040079/LeetCode_17_0079.py, Week_03/G20200343040079/LeetCode_200_0079.py, Week_03/G20200343040079/LeetCode_226_0079.py, Week_03/G20200343040079/LeetCode_22_0079.py, Week_03/G20200343040079/LeetCode_236_0079.py, Week_03/G20200343040079/LeetCode_264_0079.py, Week_03/G20200343040079/LeetCode_297_0079.py, Week_03/G20200343040079/LeetCode_347_0079.py, Week_03/G20200343040079/LeetCode_40_0079.py, Week_03/G20200343040079/LeetCode_429_0079.py, Week_03/G20200343040079/LeetCode_46_0079.py, Week_03/G20200343040079/LeetCode_47_0079.py, Week_03/G20200343040079/LeetCode_50_0079.py, Week_03/G20200343040079/LeetCode_51_0079.py, Week_03/G20200343040079/LeetCode_589_0079.py, Week_03/G20200343040079/LeetCode_590_0079.py, Week_03/G20200343040079/LeetCode_70_0079.py, Week_03/G20200343040079/LeetCode_77_0079.py, Week_03/G20200343040079/LeetCode_78_0079.py, Week_03/G20200343040079/LeetCode_94_0079.py, Week_03/G20200343040079/LeetCode_98_0079.py, Week_03/G20200343040079/NOTE.md
=> 0079_Week03（py）

Week_02/G20200343040037/LeetCode_1_0037.cpp, Week_02/G20200343040037/LeetCode_42_0037.cpp, Week_02/G20200343040037/LeetCode_49_0037.cpp, Week_02/G20200343040037/LeetCode_641_0037.cpp
leetcode 1, 42, 49, 641提交作业....
=> 0037_Week02（c++）

Week_03/G20200343040189/LeetCode_105_0189.java, Week_03/G20200343040189/LeetCode_144_0189.java, Week_03/G20200343040189/LeetCode_236_0189.java, Week_03/G20200343040189/LeetCode_589_0189.java, Week_03/G20200343040189/LeetCode_590_0189.java, Week_03/G20200343040189/NOTE.md
=> 0189_week 03(Java)

Week_03/G20200343040267/LeeCode_046_0267.java, Week_03/G20200343040267/LeeCode_047_0267.java, Week_03/G20200343040267/LeeCode_077_0267.java, Week_03/G20200343040267/LeeCode_105_0267.java, Week_03/G20200343040267/LeeCode_144_0267.java, Week_03/G20200343040267/LeeCode_236_0267.java, Week_03/G20200343040267/LeeCode_429_0267.java, Week_03/G20200343040267/LeeCode_589_0267.java, Week_03/G20200343040267/LeeCode_590_0267.java
=> 0267_Week03（Java）

Week_03/G20200343040205/NOTE.md, Week_03/G20200343040205/leetcode_week03_0205.java
=> [leetcode_week03_0205_java]

Week_03/G20200343040105/lowest-common-ancestor-of-a-binary-tree.cpp, Week_03/G20200343040105/n-ary-tree-postorder-traversal.cpp, Week_03/G20200343040105/n-ary-tree-preorder-traversal.cpp
=> 0105_Week03(c++)

Week_03/G20200343040147/LeetCode_144_0147.java, Week_03/G20200343040147/LeetCode_236_0147.java, Week_03/G20200343040147/LeetCode_429_0147.java, Week_03/G20200343040147/LeetCode_46_0147.java, Week_03/G20200343040147/LeetCode_47_0147.java, Week_03/G20200343040147/LeetCode_589_0147.java, Week_03/G20200343040147/LeetCode_590_0147.java, Week_03/G20200343040147/LeetCode_77_0147.java
=> 0147_Week03（java）

Week_03/G20200343040069/LeetCode_105_0069.java, Week_03/G20200343040069/LeetCode_144_0069.java, Week_03/G20200343040069/LeetCode_236_0069.java, Week_03/G20200343040069/LeetCode_429_0069.java, Week_03/G20200343040069/LeetCode_46_0069.java, Week_03/G20200343040069/LeetCode_47_0069.java, Week_03/G20200343040069/LeetCode_589_0069.java, Week_03/G20200343040069/LeetCode_590_0069.java, Week_03/G20200343040069/LeetCode_77_0069.java
=> 0069_week03(java)

Week_03/G20200343040241/LeetCode_105_0241.java, Week_03/G20200343040241/LeetCode_144_0241.java, Week_03/G20200343040241/LeetCode_429_0241.java, Week_03/G20200343040241/LeetCode_46_0241.java, Week_03/G20200343040241/LeetCode_47_0241.java, Week_03/G20200343040241/LeetCode_589_0241.java, Week_03/G20200343040241/LeetCode_590_0241.java, Week_03/G20200343040241/LeetCode_999_0241.java, Week_04/G20200343040241/LeetCode_122_0241.java, Week_04/G20200343040241/LeetCode_127_0241.java, Week_04/G20200343040241/LeetCode_200_0241.java, Week_04/G20200343040241/LeetCode_22_0241.java, Week_04/G20200343040241/LeetCode_455_0241.java, Week_04/G20200343040241/LeetCode_70_0241.java, Week_04/G20200343040241/LeetCode_860_0241.java, Week_04/G20200343040241/NOTE.md
=> 0241_Week04（java）

Week_04/G20200343040147/LeetCode_122_0147.java, Week_04/G20200343040147/LeetCode_127_0147.java, Week_04/G20200343040147/LeetCode_200_0147.java, Week_04/G20200343040147/LeetCode_33_0147.java, Week_04/G20200343040147/LeetCode_455_0147.java, Week_04/G20200343040147/LeetCode_45_0147.java, Week_04/G20200343040147/LeetCode_529_0147.java, Week_04/G20200343040147/LeetCode_55_0147.java, Week_04/G20200343040147/LeetCode_74_0147.java, Week_04/G20200343040147/LeetCode_860_0147.java
=> 0147_Week04（java）

Week_03/G20200343040037/LeetCode_105_0037.cpp, Week_03/G20200343040037/LeetCode_236_0037.cpp, Week_03/G20200343040037/LeetCode_589_0037.cpp, Week_03/G20200343040037/LeetCode_590_0037.cpp
=> 0037_Week03(C++)

Week_04/G20200343040273/LeetCode_122_0273.php, Week_04/G20200343040273/LeetCode_200_0273.php
=> 0273_week04(php)

Week_04/G20200343040043/LeetCode_455_0043.go, Week_04/G20200343040043/LeetCode_860_0043.go
=> 0043_Week04（golang）

Week_04/G20200343040115/AssignCookies.java, Week_04/G20200343040115/BestTimeToBuyAndSellStockIi.java, Week_04/G20200343040115/JumpGame.java, Week_04/G20200343040115/LemonadeChange.java, Week_04/G20200343040115/Minesweeper.java, Week_04/G20200343040115/NumberOfIslands.java, Week_04/G20200343040115/SearchA2dMatrix.java, Week_04/G20200343040115/SearchInRotatedSortedArray.java, Week_04/G20200343040115/WalkingRobotSimulation.java, Week_04/G20200343040115/WordLadder.java
=> 0115_Week04(java)

Week_04/G20200343040257/LeetCode_122_0257.java, Week_04/G20200343040257/LeetCode_153_0257.java, Week_04/G20200343040257/LeetCode_22_0257.java, Week_04/G20200343040257/LeetCode_433_0257.java, Week_04/G20200343040257/LeetCode_455_0257.java, Week_04/G20200343040257/LeetCode_860_0257.java, Week_04/G20200343040257/NOTE.md
=> 0257_Week04(Java)

Week_03/G20200343040145/LeetCode_144_0145.java, Week_03/G20200343040145/LeetCode_429_0145.java, Week_03/G20200343040145/LeetCode_589_0145.java, Week_03/G20200343040145/LeetCode_590_0145.java, Week_04/G20200343040145/LeetCode_122_0145.java, Week_04/G20200343040145/LeetCode_455_0145.java, Week_04/G20200343040145/LeetCode_55_0145.java, Week_04/G20200343040145/LeetCode_860_0145.java
=> 0145_week04(java)

Week_04/G20200343040069/LeetCode_122_0069.java, Week_04/G20200343040069/LeetCode_126_0069.java, Week_04/G20200343040069/LeetCode_127_0069.java, Week_04/G20200343040069/LeetCode_153_0069.java, Week_04/G20200343040069/LeetCode_200_0069.java, Week_04/G20200343040069/LeetCode_33_0069.java, Week_04/G20200343040069/LeetCode_455_0069.java, Week_04/G20200343040069/LeetCode_45_0069.java, Week_04/G20200343040069/LeetCode_529_0069.java, Week_04/G20200343040069/LeetCode_55_0069.java, Week_04/G20200343040069/LeetCode_74_0069.java, Week_04/G20200343040069/LeetCode_860_0069.java, Week_04/G20200343040069/LeetCode_874_0069.java
=> 0069_week4(java)

Week_04/G20200343040229/LeetCode_122_0229.go, Week_04/G20200343040229/LeetCode_62_0229.go, Week_04/G20200343040229/LeetCode_74_0229.go, Week_04/G20200343040229/LeetCode_860_0229.go, Week_04/G20200343040229/LeetCode_8_0229.go, Week_04/G20200343040229/LeetCode_912_0229.go
=> 0229_Week04(Go)

Week_04/G20200343040105/findMin.cpp, Week_04/G20200343040105/jump-game-i.cpp, Week_04/G20200343040105/jump-game-ii.cpp, Week_04/G20200343040105/lemonadeChange.cpp, Week_04/G20200343040105/walking-robot-simulation.cpp
=> 0105_Week04(c++)

Week_04/G20200343040185/Leetcode_122_0185.js, Week_04/G20200343040185/Leetcode_455_0185.js, Week_04/G20200343040185/Leetcode_45_0185.js, Week_04/G20200343040185/Leetcode_55_0185.js, Week_04/G20200343040185/Leetcode_860_0185.js
=> 0185_Week04（js)

Week_04/G20200343040247/LeetCode_122_0247.js, Week_04/G20200343040247/LeetCode_455_0247.js, Week_04/G20200343040247/LeetCode_860_0247.js
=> 0247_Week04(js)

Week_04/G20200343040173/LeetCode_122_0173_1.java, Week_04/G20200343040173/LeetCode_122_0173_2.java, Week_04/G20200343040173/LeetCode_200_0173_1.java, Week_04/G20200343040173/LeetCode_200_0173_2.java, Week_04/G20200343040173/LeetCode_860_0173_1.java
=> 0173_Week04(Java)

Week_04/G20200343040251/LeetCode_122_0251.js, Week_04/G20200343040251/LeetCode_126_0251.js, Week_04/G20200343040251/LeetCode_127_0251.js, Week_04/G20200343040251/LeetCode_153_0251.js, Week_04/G20200343040251/LeetCode_200_0251.js, Week_04/G20200343040251/LeetCode_33_0251.js, Week_04/G20200343040251/LeetCode_455_0251.js, Week_04/G20200343040251/LeetCode_45_0251.js, Week_04/G20200343040251/LeetCode_529_0251.js, Week_04/G20200343040251/LeetCode_55_0251.js, Week_04/G20200343040251/LeetCode_74_0251.js, Week_04/G20200343040251/LeetCode_860_0251.js, Week_04/G20200343040251/LeetCode_874_0251.js
=> 0251_Week04(js)

Week_04/G20200343040271/LeetCode_153_0271.java, Week_04/G20200343040271/LeetCode_200_0271.java, Week_04/G20200343040271/LeetCode_33_0271.java, Week_04/G20200343040271/LeetCode_74_0271.java
=> 0271_Week04(Java)

Week_04/G20200343040091/LeetCode_127_0091.java, Week_04/G20200343040091/LeetCode_529_0091.java
=> 0091_Week04（java）

Week_04/G20200343040075/LeetCode_122_0075.cs, Week_04/G20200343040075/LeetCode_127_0075.cs, Week_04/G20200343040075/LeetCode_200_0075.cs, Week_04/G20200343040075/LeetCode_455_0075.cs, Week_04/G20200343040075/LeetCode_860_0075.cs, Week_04/G20200343040075/LeetCode_874_0075.cs, Week_04/G20200343040075/NOTE.md
=> 0075_Week04（csharp）

Week_06/G20200343040043/LeetCode_64_0043.go, Week_06/G20200343040043/LeetCode_91_0043.go
=> 0043_Week06（golang）

Week_06/G20200343040289/221.maximal-square.js, Week_06/G20200343040289/64.minimum-path-sum.js, Week_06/G20200343040289/91.decode-ways.js
https://leetcode-cn.com/problems/minimum-path-sum/
https://leetcode-cn.com/problems/decode-ways
https://leetcode-cn.com/problems/maximal-square/
=> week 6 homework

Week_06/G20200343040147/LeetCode_221_0147.java, Week_06/G20200343040147/LeetCode_621_0147.java, Week_06/G20200343040147/LeetCode_647_0147.java, Week_06/G20200343040147/LeetCode_64_0147.java, Week_06/G20200343040147/LeetCode_91_0147.java
=> 0147_Week06（java）

Week_06/G20200343040145/LeetCode_221_0145.java, Week_06/G20200343040145/LeetCode_647_0145.java, Week_06/G20200343040145/LeetCode_64_0145.java, Week_06/G20200343040145/LeetCode_91_0145.java
=> 0145_Week06(java)

Week_06/G20200343040227/LeetCode_221_0227.java, Week_06/G20200343040227/LeetCode_621_0227.java, Week_06/G20200343040227/LeetCode_647_0227.java, Week_06/G20200343040227/LeetCode_64_0227.java, Week_06/G20200343040227/LeetCode_91_0227.java
=> 0227_Week6(java)

Week_06/G20200343040271/LeetCode_32_0271.java, Week_06/G20200343040271/LeetCode_64_0271.java
=> 0271_Week06（java）

Week_06/G20200343040105/maximalSquare.cpp, Week_06/G20200343040105/minPathSum.cpp, Week_06/G20200343040105/numDecodings.cpp
=> 0105_Week06(cpp)

Week_06/G20200343040229/LeetCode_64_0229.go, Week_06/G20200343040229/LeetCode_91_0229.go
=> 0229_Week06（Go）

Week_06/G20200343040079/LeetCode_1143_0079.py, Week_06/G20200343040079/LeetCode_120_0079.py, Week_06/G20200343040079/LeetCode_152_0079.py, Week_06/G20200343040079/LeetCode_198_0079.py, Week_06/G20200343040079/LeetCode_213_0079.py, Week_06/G20200343040079/LeetCode_221_0079.py, Week_06/G20200343040079/LeetCode_279_0079.py, Week_06/G20200343040079/LeetCode_322_0079.py, Week_06/G20200343040079/LeetCode_337_0079.py, Week_06/G20200343040079/LeetCode_518_0079.py, Week_06/G20200343040079/LeetCode_53_0079.py, Week_06/G20200343040079/LeetCode_621_0079.py, Week_06/G20200343040079/LeetCode_62_0079.py, Week_06/G20200343040079/LeetCode_63_0079.py, Week_06/G20200343040079/LeetCode_647_0079.py, Week_06/G20200343040079/LeetCode_64_0079.py, Week_06/G20200343040079/LeetCode_70_0079.py, Week_06/G20200343040079/LeetCode_72_0079.py, Week_06/G20200343040079/LeetCode_91_0079.py, Week_06/G20200343040079/LeetCode_980_0079.py
=> 0079_Week06（py）

Week_03/G20200343040185/LeetCode_144_0185.js, Week_03/G20200343040185/LeetCode_33_0185.js, Week_07/G20200343040185/Leetcode_64_0185.js, Week_07/G20200343040185/Leetcode_91_0185.js
=> Week03_0185(js)

Week_06/G20200343040075/LeetCode_64_0075.cs, Week_06/G20200343040075/LeetCode_91_0075.cs, Week_06/G20200343040075/NOTE.md
做完实战题，才发现作业都是新题，赶着最后时刻提交两道作业，其余的后续努力补上。。。
=> 0075_Week06（csharp）

Week_06/G20200343040173/LeetCode_64_0173_1.java, Week_06/G20200343040173/LeetCode_64_0173_2.java, Week_06/G20200343040173/LeetCode_64_0173_3.java, Week_06/G20200343040173/LeetCode_64_0173_4.java, Week_06/G20200343040173/LeetCode_91_0173_1.java, Week_06/G20200343040173/LeetCode_91_0173_2.java, Week_06/G20200343040173/LeetCode_91_0173_3.java
=> 0173_Week06(Java)

Week_06/G20200343040251/LeetCode_221_0251.js, Week_06/G20200343040251/LeetCode_621_0251.js, Week_06/G20200343040251/LeetCode_647_0251.js, Week_06/G20200343040251/LeetCode_64_0251.js, Week_06/G20200343040251/LeetCode_91_0251.js
=> 0251_Week06(js)

Week_06/G20200343040069/LeetCode_32_0069.java, Week_06/G20200343040069/LeetCode_64_0069.java, Week_06/G20200343040069/LeetCode_72_0069.java
=> 0069_week6(java)

Week_07/G20200343040147/LeetCode_127_0147.java, Week_07/G20200343040147/LeetCode_208_0147.java, Week_07/G20200343040147/LeetCode_433_0147.java, Week_07/G20200343040147/LeetCode_547_0147.java
=> 0147_Week07（java）

Week_04/G20200343040037/LeetCode_122_0037.cpp, Week_04/G20200343040037/LeetCode_455_0037.cpp, Week_04/G20200343040037/LeetCode_860_0037.cpp, Week_04/G20200343040037/LeetCode_874_0037.cpp
=> 0037_Week04(C++)

Week_07/G20200343040115/FriendCircles.java, Week_07/G20200343040115/ImplementTriePrefixTree.java, Week_07/G20200343040115/NumberOfIslands.java, Week_07/G20200343040115/NumberOfIslands65838461.txt
=> 0115_Week07(java)

Week_07/G20200343040273/LeetCode_130_0273.php, Week_07/G20200343040273/LeetCode_22_0273.php, Week_07/G20200343040273/LeetCode_547_0273.php
=> 0273_Week07(php)

Week_07/G20200343040033/LeetCode_2_0033.py, Week_07/G20200343040033/LeetCode_3_0033.py, Week_07/G20200343040033/LeetCode_4_0033.py
=> 0033_Week07(py3)

Week_07/G20200343040075/LeetCode_200_0075.cs, Week_07/G20200343040075/LeetCode_208_0075.cs, Week_07/G20200343040075/LeetCode_70_0075.cs, Week_07/G20200343040075/NOTE.md
=> 0075_Week01（csharp）

Week_07/G20200343040271/LeetCode_127_0271.java, Week_07/G20200343040271/LeetCode_22_0271.java, Week_07/G20200343040271/LeetCode_70_0271.java
=> 0271_Week07(Java)

Week_07/G20200343040229/LeetCode_22_0229.go, Week_07/G20200343040229/LeetCode_70_0229.go
=> 0229_Week07（Go）

Week_07/G20200343040105/Trie.cpp, Week_07/G20200343040105/sloveNQueens.cpp, Week_07/G20200343040105/solveSudoku.cpp, Week_07/G20200343040105/word-ladder.cpp, Week_07/G20200343040105/word-search-ii.cpp
=> 0105_Week07(C++)

Week_07/G20200343040251/LeetCode_130_0251.js, Week_07/G20200343040251/LeetCode_200_0251.js, Week_07/G20200343040251/LeetCode_22_0251.js, Week_07/G20200343040251/LeetCode_36_0251.js, Week_07/G20200343040251/LeetCode_547_0251.js
=> 0251_Week07(js)

Week_04/G20200343040079/LeetCode_127_0079.py, Week_04/G20200343040079/LeetCode_433_0079.py, Week_04/G20200343040079/LeetCode_45_0079.py, Week_04/G20200343040079/LeetCode_515_0079.py, Week_07/G20200343040079/LeetCode_1091_0079.py, Week_07/G20200343040079/LeetCode_130_0079.py, Week_07/G20200343040079/LeetCode_200_0079.py, Week_07/G20200343040079/LeetCode_208_0079.py, Week_07/G20200343040079/LeetCode_212_0079.py, Week_07/G20200343040079/LeetCode_36_0079.py, Week_07/G20200343040079/LeetCode_37_0079.py, Week_07/G20200343040079/LeetCode_547_0079.py, Week_07/G20200343040079/LeetCode_773_0079.py
=> 0079_Week07（py）

Week_07/G20200343040069/LeetCode_127_0069.java, Week_07/G20200343040069/LeetCode_200_0069.java, Week_07/G20200343040069/LeetCode_51_0069.java
=> 0069_week7(java)

Week_07/G20200343040009/Java/LeetCode70.java, Week_07/G20200343040009/Java/Trie.java, Week_08/G20200343040009/src/Java/BubbleSort.java, Week_08/G20200343040009/src/Java/InsertionSort.java, Week_08/G20200343040009/src/Java/LeetCode190.java, Week_08/G20200343040009/src/Java/LeetCode191.java, Week_08/G20200343040009/src/Java/LeetCode231.java, Week_08/G20200343040009/src/Java/SelectionSort.java, algorithm007-class01.iml
=> fix:push作业

Week_08/G20200343040145/LeetCode_190_0145.java, Week_08/G20200343040145/LeetCode_191_0145.java, Week_08/G20200343040145/LeetCode_231_0145.java
=> 0145_Week08(java)

Week_08/G20200343040273/LeetCode_190_0273.php, Week_08/G20200343040273/LeetCode_191_0273.php, Week_08/G20200343040273/LeetCode_56_0273.php
=> 0273_week08(php)

Week_08/G20200343040147/LeetCode_1122_0147.java, Week_08/G20200343040147/LeetCode_1244_0147.java, Week_08/G20200343040147/LeetCode_190_0147.java, Week_08/G20200343040147/LeetCode_191_0147.java, Week_08/G20200343040147/LeetCode_231_0147.java, Week_08/G20200343040147/LeetCode_242_0147.java
=> 0147_Week08（java）

Week_08/G20200343040069/LeetCode_1122_0069.java, Week_08/G20200343040069/LeetCode_146_0069.java, Week_08/G20200343040069/LeetCode_190_0069.java, Week_08/G20200343040069/LeetCode_191_0069.java, Week_08/G20200343040069/LeetCode_231_0069.java, Week_08/G20200343040069/LeetCode_242_0069.java, Week_08/G20200343040069/LeetCode_493_0069.java, Week_08/G20200343040069/LeetCode_56_0069.java
=> 0069_week8(java)

Week_08/G20200343040229/LeetCode_1122_0229.go, Week_08/G20200343040229/LeetCode_242_0229.go, Week_08/G20200343040229/LeetCode_451_0229.go
=> 0229_Week08（Go）

Week_08/G20200343040091/ LeetCode_146_0091.java, Week_08/G20200343040091/ LeetCode_56_0091.java
=> 0091_Week08（java）

Week_08/G20200343040063/LeetCode_146_0063.java, Week_08/G20200343040063/LeetCode_56_0063.java
=> 0063_Week08(Java)

Week_08/G20200343040251/LeetCode_1122_0251.js, Week_08/G20200343040251/LeetCode_146_0251.js, Week_08/G20200343040251/LeetCode_190_0251.js, Week_08/G20200343040251/LeetCode_191_0251.js, Week_08/G20200343040251/LeetCode_231_0251.js, Week_08/G20200343040251/LeetCode_242_0251.js, Week_08/G20200343040251/LeetCode_56_0251.js
=> 0251_Week08(js)

Week_08/G20200343040271/LeetCode_146_0271.java, Week_08/G20200343040271/LeetCode_191_0271.java, Week_08/G20200343040271/LeetCode_231_0271.java
=> 0271_Week08(Java)

Week_01/G20200343040079/LeetCode_189_0079.py, Week_08/G20200343040079/LeetCode_1122_0079.py, Week_08/G20200343040079/LeetCode_146_0079.py, Week_08/G20200343040079/LeetCode_190_0079.py, Week_08/G20200343040079/LeetCode_191_0079.py, Week_08/G20200343040079/LeetCode_231_0079.py, Week_08/G20200343040079/LeetCode_242_0079.py, Week_08/G20200343040079/LeetCode_338_0079.py, Week_08/G20200343040079/LeetCode_493_0079.py, Week_08/G20200343040079/LeetCode_52_0079.py, Week_08/G20200343040079/LeetCode_56_0079.py, Week_08/G20200343040079/LeetCode_912_0079.py
=> 0079_Week08（py）

Week_06/G20200343040221/LeetCode_221_0221.java, Week_06/G20200343040221/LeetCode_621_0221.java, Week_06/G20200343040221/LeetCode_647_0221.java, Week_06/G20200343040221/LeetCode_64_0221.java, Week_06/G20200343040221/LeetCode_91_0221.java
=> 0221_Week06(Java)

Week_09/G20200343040105/firstUniqChar.cpp, Week_09/G20200343040105/lengthOfLIS.cpp, Week_09/G20200343040105/numDecodings.cpp, Week_09/G20200343040105/reverseStr.cpp
=> 0105_Week09(c++)

Week_09/G20200343040069/LeetCode_05_0069.java, Week_09/G20200343040069/LeetCode_08_0069.java, Week_09/G20200343040069/LeetCode_151_0069.java
=> 0069_week9(java)

Week_09/G20200343040251/LeetCode_300_0251.js, Week_09/G20200343040251/LeetCode_438_0251.js, Week_09/G20200343040251/LeetCode_5_0251.js, Week_09/G20200343040251/LeetCode_8_0251.js, Week_09/G20200343040251/LeetCode_91_0251.js
=> 0251_Week09(js)

Week_02/G20200343040063/LeetCode_1_0063.java, Week_02/G20200343040063/LeetCode_42_0063.java, Week_02/G20200343040063/LeetCode_49_0063.java, Week_02/G20200343040063/LeetCode_641_0063.java, Week_04/G20200343040063/LeetCode_127_0063.java, Week_04/G20200343040063/LeetCode_200_0063.java, Week_06/G20200343040063/LeetCode_64_0063.java, Week_06/G20200343040063/LeetCode_91_0063.java
=> 0063_Week09(Java)

Week_09/G20200343040271/LeetCode_151_0271.java, Week_09/G20200343040271/LeetCode_387_0271.java, Week_09/G20200343040271/LeetCode_541_0271.java, Week_09/G20200343040271/LeetCode_557_0271.java
=> 0271_Week09（Java）

Week_09/G20200343040229/LeetCode_151_0229.go, Week_09/G20200343040229/LeetCode_91_0229.go
=> 0229_Week09（Go）

Week_09/G20200343040173/LeetCode_151_0173_1.java, Week_09/G20200343040173/LeetCode_151_0173_2.java, Week_09/G20200343040173/LeetCode_151_0173_3.java, Week_09/G20200343040173/LeetCode_387_0173_1.java, Week_09/G20200343040173/LeetCode_541_0173_1.java
=> 0173_Week09(Java)

Week_06/G20200343040037/LeetCode_589_0037.cpp, Week_06/G20200343040037/LeetCode_590_0037.cpp, Week_06/G20200343040037/LeetCode_64_0037.cpp, Week_06/G20200343040037/LeetCode_91_0037.cpp, Week_07/G20200343040037/Leetcode_208_0037.cpp, Week_07/G20200343040037/Leetcode_547_0037.cpp, Week_08/G20200343040037/LeetCode_146_0037.cpp, Week_08/G20200343040037/LeetCode_51_0037.cpp, Week_09/G20200343040037/Leetcode_300_0037.cpp, Week_09/G20200343040037/Leetcode_91_0037.cpp
=> 0037_Week06(c++)

Week_08/G20200343040289/number-of-1-bits.js, Week_08/G20200343040289/power-of-two.js, Week_09/G20200343040289/first-unique-character-in-a-string.js, Week_09/G20200343040289/reverse-string-ii.js
=> 0289_week 8 & 9 home work (补缴)

Week_07/G20190379010121/LeetCode_208_1121.java, Week_07/G20190379010121/LeetCode_70_1121.java, Week_07/G20190379010121/NOTE.md
=> 1121_Week07（java）

Week_06/G20200343040091/ LeetCode_221_0091.java, Week_06/G20200343040091/ LeetCode_621_0091.java, Week_07/G20200343040091/ LeetCode_130_0091.java, Week_07/G20200343040091/LeetCode_36_0091.java, Week_09/G20200343040091/LeetCode_300_0091.java, Week_09/G20200343040091/LeetCode_91_0091.java
=> 0091_Week09（java）

Week_07/G20200343040063/LeetCode_200_0063.java, Week_07/G20200343040063/LeetCode_547_0063.java
=> 0063_Week07(Java)
